site_name: MLMD document
nav:
- Introduction: introduction.md
- User Guide:
    - Data Preliminary: user-guide/data preliminary.md
    - Feature Engineering: user-guide/feature engineering.md
    - Regression: user-guide/regression.md
    - Classification: user-guide/classification.md
    - Active Learning: user-guide/active learning.md
    # - Explainable machine learning: user-guide/explainable machine 
- About:
    - License: about/license.md
    - Release Notes: about/release-notes.md
theme: readthedocs
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.superfences
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


